### ISSUE TITLE
Hey I'm having some trouble

### ISSUE THREAD

**Issue by cinojosa0705** [mnlwldr/coinbase#1]
go build -o main .
# main
./main.go:5:2: imported and not used: "github.com/mnlwldr/coinbase"
./main.go:9:19: undefined: Get
make: *** [Makefile:6: main] Error 2

what can I do to fix this? thanks!

**Comment by mnlwldr** [comment]
Hi  @cinojosa0705, 

there was a typo in the Readme.md. 

The following code should work: 
```go
package main

import (
	"log"

	"github.com/mnlwldr/coinbase"
)

func main() {

	shib, err := coinbase.Get("SHIB-EUR")

	if err != nil {
		log.Println(err)
	}

	log.Printf("%.7f\n", shib.Amount)
}
```
